# Generated by Django 5.2.7 on 2025-11-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='AvailabilityDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'availability_days',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(db_column='courseID', primary_key=True, serialize=False)),
                ('courseName', models.CharField(db_column='courseName', max_length=255)),
                ('college', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hallID', models.AutoField(db_column='hallID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'halls',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructorID', models.AutoField(db_column='instructorID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'instructors',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.AutoField(db_column='studentID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='AvailabilityTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('availabilityId', models.ForeignKey(db_column='availabilityId', on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='api.availabilityday')),
            ],
            options={
                'db_table': 'availability_times',
            },
        ),
        migrations.CreateModel(
            name='CourseMappingRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('course', models.ForeignKey(db_column='courseID', on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
            options={
                'db_table': 'course_mapping_relations',
            },
        ),
        migrations.CreateModel(
            name='CourseMappings',
            fields=[
                ('mappingID', models.AutoField(db_column='mappingID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('courses', models.ManyToManyField(related_name='course_mappings', through='api.CourseMappingRelation', to='api.course')),
            ],
            options={
                'db_table': 'course_mappings',
            },
        ),
        migrations.AddField(
            model_name='coursemappingrelation',
            name='course_mapping',
            field=models.ForeignKey(db_column='mappingID', on_delete=django.db.models.deletion.CASCADE, to='api.coursemappings'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examID', models.AutoField(db_column='examID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('college', models.CharField(max_length=255)),
                ('courseID', models.ForeignKey(db_column='courseID', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.course')),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.AddField(
            model_name='availabilityday',
            name='instructorID',
            field=models.ForeignKey(db_column='instructorID', on_delete=django.db.models.deletion.CASCADE, related_name='availability_days', to='api.instructor'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('course', models.ForeignKey(db_column='courseCourseID', on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('student', models.ForeignKey(db_column='studentStudentID', on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'Enrollment',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', through='api.Enrollment', to='api.student'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemappingrelation',
            unique_together={('course_mapping', 'course')},
        ),
        migrations.CreateModel(
            name='InstructorOnHall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('examID', models.ForeignKey(db_column='examID', on_delete=django.db.models.deletion.CASCADE, related_name='instructor_on_halls', to='api.exam')),
                ('hallID', models.ForeignKey(db_column='hallID', on_delete=django.db.models.deletion.CASCADE, related_name='instructor_on_halls', to='api.hall')),
                ('instructorID', models.ForeignKey(db_column='instructorID', on_delete=django.db.models.deletion.CASCADE, related_name='instructor_on_halls', to='api.instructor')),
            ],
            options={
                'db_table': 'instructor_on_halls',
                'unique_together': {('examID', 'hallID', 'instructorID')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleID', models.AutoField(db_column='scheduleID', primary_key=True, serialize=False)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('examID', models.ForeignKey(db_column='examID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.exam')),
                ('hallID', models.ForeignKey(blank=True, db_column='hallID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.hall')),
                ('studentID', models.ForeignKey(db_column='studentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.student')),
            ],
            options={
                'db_table': 'schedules',
                'unique_together': {('examID', 'studentID')},
            },
        ),
    ]
